version: "3.9"
services:
  postgres:
    image: postgres:14.5
    hostname: entirety-db
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - entirety

  entirety:
    image: ghcr.io/n5geh/n5geh.tools.entirety:latest
    restart: unless-stopped
    expose:
      - 8000
    env_file:
      - .env
    volumes:
      - static:${STATIC_ROOT:-/var/entirety/static/}
      - media:${MEDIA_ROOT:-/var/entirety/media/}
    depends_on:
      - postgres
    networks:
      - entirety

  nginx:
    image: nginx:1.23.1
    hostname: ng
    ports:
      - "80:80"
    volumes:
      - ../configs/nginx:/etc/nginx/templates/
      - static:${STATIC_ROOT:-/var/entirety/static/}
      - media:${MEDIA_ROOT:-/var/entirety/media/}
    environment:
      NGINX_ENVSUBST_TEMPLATE_SUFFIX: ".conf"
      WEB_HOST: ${WEB_HOST:-localhost}
    depends_on:
      - entirety
    networks:
      - entirety

volumes:
  static:
  pgdata:
  media:

networks:
  entirety:
